import { convert,createUnitIndex,normalizeToBase } from '../../data/units/registry.js';import { checkQuantityDimensions,sanityCheck } from '../validation/dimensional-analysis.js';
export function normalizeKnowns(raw={},variableIndex=null,unitIndex=createUnitIndex()){const knowns=new Map();for(const[id,entry]of Object.entries(raw)){if(!entry||entry.value===''||entry.value===null||entry.value===undefined)continue;const numeric=Number(entry.value);if(!Number.isFinite(numeric))throw new Error(`Invalid numeric value for ${id}`);const variable=variableIndex?.byId?.get(id);let normalized={value:numeric,unit:entry.unit||null};if(entry.unit){const base=normalizeToBase(numeric,entry.unit,unitIndex),check=checkQuantityDimensions({variable,dimensions:base.dimensions});if(!check.ok)throw new Error(`${id}: ${check.warnings.join(' ')}`);normalized={value:base.value,unit:variable?.commonUnits?.[0]||entry.unit,sourceUnit:entry.unit};}knowns.set(id,normalized);}return knowns;}
export function unresolvedVariables(equation,knowns,constants=new Map()){return equation.variables.filter(id=>!knowns.has(id)&&!constants.has(id));}
export function findDirectCandidates(target,equations,knowns,constants=new Map()){return equations.filter(eq=>eq.variables.includes(target)).map(equation=>({equation,unresolved:unresolvedVariables(equation,knowns,constants)})).filter(x=>x.unresolved.length===1&&x.unresolved[0]===target);}
export function rankCandidates(candidates,target,context={}){return[...candidates].sort((a,b)=>{const score=item=>{const eq=item.equation,text=(context.text||'').toLowerCase();let v=eq.complexity||1;if(context.domains?.includes(eq.domain))v-=.5;v-=Math.min((eq.keywords||[]).filter(k=>text.includes(k.toLowerCase())).length,5)*.1;return v+(eq.targetMap?.[target]?.length||0)*.01;};return score(a)-score(b)||a.equation.id.localeCompare(b.equation.id);});}
const divide=(a,b,label)=>{if(Math.abs(b)<1e-15)throw new Error(`Division by zero while solving ${label}`);return a/b;};const root=x=>{if(x<0)throw new Error('Square root received a negative value. Check inputs or physical assumptions.');return Math.sqrt(x);};const angleCos=a=>Math.cos(a);
export function solveDirect(equation,target,knowns,constants=new Map()){const g=id=>knowns.get(id)?.value??constants.get(id)?.value;const vi=g('velocity_initial'),vf=g('velocity_final'),a=g('acceleration'),t=g('time'),dx=g('displacement'),m=g('mass'),F=g('force'),E=g('energy'),h=g('height'),grav=g('g0');switch(equation.id){
case'kinematics.velocity_time':if(target==='velocity_final')return vi+a*t;if(target==='velocity_initial')return vf-a*t;if(target==='acceleration')return divide(vf-vi,t,'acceleration');if(target==='time')return divide(vf-vi,a,'time');break;
case'kinematics.displacement_velocity':if(target==='displacement')return((vi+vf)/2)*t;if(target==='velocity_initial')return 2*divide(dx,t,'initial velocity')-vf;if(target==='velocity_final')return 2*divide(dx,t,'final velocity')-vi;if(target==='time')return divide(2*dx,vi+vf,'time');break;
case'kinematics.position_time':{const xi=g('position_initial'),xf=g('position_final');if(target==='position_final')return xi+vi*t+.5*a*t*t;break;}
case'kinematics.velocity_displacement':if(target==='velocity_final')return root(vi*vi+2*a*dx);if(target==='velocity_initial')return root(vf*vf-2*a*dx);if(target==='acceleration')return divide(vf*vf-vi*vi,2*dx,'acceleration');if(target==='displacement')return divide(vf*vf-vi*vi,2*a,'displacement');break;
case'kinematics.average_velocity':{const av=g('velocity_average');if(target==='velocity_average')return divide(dx,t,'average velocity');if(target==='displacement')return av*t;if(target==='time')return divide(dx,av,'time');break;}
case'dynamics.newton_second':if(target==='force')return m*a;if(target==='mass')return divide(F,a,'mass');if(target==='acceleration')return divide(F,m,'acceleration');break;
case'dynamics.friction':{const f=g('friction_force'),mu=g('coefficient_friction'),N=g('normal_force');if(target==='friction_force')return mu*N;if(target==='coefficient_friction')return divide(f,N,'coefficient');if(target==='normal_force')return divide(f,mu,'normal force');break;}
case'dynamics.hooke':{const k=g('spring_constant'),x=g('spring_displacement');if(target==='force')return k*x;if(target==='spring_constant')return divide(F,x,'spring constant');if(target==='spring_displacement')return divide(F,k,'spring displacement');break;}
case'energy.kinetic':if(target==='energy')return .5*m*vf*vf;if(target==='mass')return divide(2*E,vf*vf,'mass');if(target==='velocity_final')return root(divide(2*E,m,'velocity'));break;
case'energy.gravitational':if(target==='energy')return m*grav*h;if(target==='mass')return divide(E,grav*h,'mass');if(target==='height')return divide(E,m*grav,'height');break;
case'energy.work':{const W=g('work'),Fa=g('force_applied'),theta=g('angle');if(target==='work')return Fa*dx*angleCos(theta);if(target==='force_applied')return divide(W,dx*angleCos(theta),'force');if(target==='displacement')return divide(W,Fa*angleCos(theta),'displacement');break;}
case'energy.power':{const W=g('work'),P=g('power');if(target==='power')return divide(W,t,'power');if(target==='work')return P*t;if(target==='time')return divide(W,P,'time');break;}
case'energy.spring':{const k=g('spring_constant'),x=g('spring_displacement');if(target==='energy')return .5*k*x*x;if(target==='spring_constant')return divide(2*E,x*x,'spring constant');if(target==='spring_displacement')return root(divide(2*E,k,'spring displacement'));break;}
case'momentum.linear':{const p=g('momentum');if(target==='momentum')return m*vf;if(target==='mass')return divide(p,vf,'mass');if(target==='velocity_final')return divide(p,m,'velocity');break;}
case'momentum.impulse':{const J=g('impulse');if(target==='impulse')return F*t;if(target==='force')return divide(J,t,'force');if(target==='time')return divide(J,F,'time');break;}
case'waves.frequency_period':{const f=g('frequency'),T=g('period');if(target==='frequency')return divide(1,T,'frequency');if(target==='period')return divide(1,f,'period');break;}
case'waves.speed':{const ws=g('wave_speed'),f=g('frequency'),lambda=g('wavelength');if(target==='wave_speed')return f*lambda;if(target==='frequency')return divide(ws,lambda,'frequency');if(target==='wavelength')return divide(ws,f,'wavelength');break;}}
throw new Error(`Unsupported direct solve: ${equation.id} → ${target}`);}
export function buildSubstitution(equation,target,knowns,constants=new Map()){const inputs={};for(const id of equation.targetMap[target]||[]){const entry=knowns.get(id)||constants.get(id);inputs[id]=entry?{value:entry.value,unit:entry.unit||null}:null;}return{equationId:equation.id,target,expression:equation.expression,inputs};}
export function checkDirectSolve({equation,target,knowns,result,variableIndex}){const warnings=[];if(!Number.isFinite(result))warnings.push('Result is not finite.');const variable=variableIndex.byId.get(target);if(!variable)warnings.push(`Unknown target metadata: ${target}`);else warnings.push(...sanityCheck({variable,value:result}).warnings);return{ok:warnings.length===0,warnings};}
export function safeConvert(value,from,to,unitIndex=createUnitIndex()){try{return{ok:true,value:convert(value,from,to,unitIndex)}}catch(error){return{ok:false,error:error.message}}}
