/** Phase 6.1 — solver intelligence/orchestration.
 * Pure planning utilities: no DOM, no eval, and no mutation of the equation catalog.
 * Equation shape: {id, expression, variables:[...], domain?, domains?, priority?}.
 */
const unique=a=>[...new Set(a)];
export function normalizeEquation(eq,index=0){const variables=unique(Array.isArray(eq.variables)?eq.variables:[]);return{...eq,id:eq.id??`equation-${index}`,variables,priority:Number.isFinite(eq.priority)?eq.priority:0};}
export function buildDependencyGraph(equations=[]){const graph=new Map();for(const raw of equations){const eq=normalizeEquation(raw);for(const target of eq.variables){if(!graph.has(target))graph.set(target,new Set());for(const dependency of eq.variables)if(dependency!==target)graph.get(target).add(dependency)}}return graph;}
export function countUnknowns(equation,knowns={}){const known=new Set(Object.keys(knowns));return unique((equation.variables??[]).filter(v=>!known.has(v))).length;}
export function rankEquations(equations=[],{knowns={},target=null,domain=null}={}){return equations.map((raw,index)=>{const eq=normalizeEquation(raw,index),unknownCount=countUnknowns(eq,knowns);let score=eq.priority;if(target&&eq.variables.includes(target))score+=100;if(unknownCount===1)score+=60;else if(unknownCount===2)score+=20;else if(unknownCount>2)score-=unknownCount*10;if(domain&&eq.domain===domain)score+=25;if(domain&&Array.isArray(eq.domains)&&eq.domains.includes(domain))score+=20;score-=Math.max(0,eq.variables.length-2)*2;return{equation:eq,score,unknownCount}}).sort((a,b)=>b.score-a.score);}
export function detectCircularDependencies(equations=[]){const graph=buildDependencyGraph(equations),state=new Map(),cycles=[];const walk=(node,stack=[])=>{state.set(node,'active');for(const child of graph.get(node)??[]){if(state.get(child)==='active'){const start=stack.indexOf(child);cycles.push([...stack.slice(start),child]);}else if(state.get(child)!=='done')walk(child,[...stack,node]);}state.set(node,'done')};for(const node of graph.keys())if(!state.has(node))walk(node,[]);return{hasCycle:cycles.length>0,cycles};}

// BFS over sets of unresolved variables. A state is complete only when every dependency is known.
// This fixes the common multi-dependency bug where a path planner follows only the first missing input.
export function findShortestSolvePaths(equations=[],knowns={},target,{maxDepth=12,maxPaths=8}={}){
 const known=new Set(Object.keys(knowns)),normalized=equations.map(normalizeEquation),queue=[{pending:[target],steps:[],seen:new Set([target])}],results=[],signatures=new Set();
 while(queue.length&&results.length<maxPaths){const current=queue.shift();const pending=current.pending.filter(v=>!known.has(v));if(!pending.length){const sig=current.steps.map(e=>e.id).join('>');if(!signatures.has(sig)){signatures.add(sig);results.push(current)}continue;}if(current.steps.length>=maxDepth)continue;const variable=pending[0];const candidates=normalized.filter(eq=>eq.variables.includes(variable));for(const eq of candidates){const deps=eq.variables.filter(v=>v!==variable&&!known.has(v));if(deps.some(v=>current.seen.has(v)))continue;const seen=new Set(current.seen);deps.forEach(v=>seen.add(v));const nextPending=[...pending.slice(1),...deps];queue.push({pending:unique(nextPending),steps:[...current.steps,eq],seen});}}
 return results.sort((a,b)=>a.steps.length-b.steps.length).slice(0,maxPaths);
}
export function makeSolvePlan({equations=[],knowns={},target,domain=null,maxDepth=12}={}){if(!target)return{status:'invalid',reason:'Target is required'};const normalized=equations.map(normalizeEquation),cycleInfo=detectCircularDependencies(normalized),ranked=rankEquations(normalized,{knowns,target,domain}),direct=ranked.filter(x=>x.equation.variables.includes(target)&&x.unknownCount===1),paths=findShortestSolvePaths(normalized,knowns,target,{maxDepth});return{status:'ready',target,unknownCount:countUnknowns({variables:[target]},knowns),directCandidates:direct,shortestPath:paths[0]??null,alternativePaths:paths.slice(1),equationRanking:ranked,dependencyCycles:cycleInfo.cycles,warnings:cycleInfo.hasCycle?['The equation graph contains circular dependencies; path search will avoid revisiting variables.']:[]};}
