import { findSolvePaths } from '../../src/engine/solver/pathfinder.js';
import { executeSolvePath } from '../../src/engine/solver/path-executor.js';
import { EQUATIONS } from '../../src/data/equations/registry.js';
import { VARIABLES, createVariableIndex } from '../../src/data/variables/registry.js';
import { CONSTANTS, createConstantIndex } from '../../src/data/constants/registry.js';
import { normalizeKnowns } from '../../src/engine/solver/direct-solver.js';
const assert=(v,m)=>{if(!v)throw new Error(m)};
const knowns=normalizeKnowns({velocity_initial:{value:5},acceleration:{value:2},time:{value:3}});
const search=findSolvePaths({target:'displacement',equations:EQUATIONS,knownIds:new Set(knowns.keys())});
assert(search.paths.length>0,'Expected dependency path to displacement');
assert(search.paths[0].equationCount===2,'Expected shortest path to use two equations');
const execution=executeSolvePath({path:search.paths[0],equations:EQUATIONS,knowns,constants:createConstantIndex(CONSTANTS),variableIndex:createVariableIndex(VARIABLES)});
assert(execution.status==='solved','Expected path execution to solve');
assert(Math.abs(execution.result-24)<1e-9,`Expected 24, got ${execution.result}`);
const cyclic=[{id:'a',variables:['x','y'],targetMap:{x:['y']}},{id:'b',variables:['x','y'],targetMap:{y:['x']}}];
const cycle=findSolvePaths({target:'x',equations:cyclic,knownIds:new Set(),maxDepth:4});
assert(cycle.paths.length===0,'Cycle must not produce a fake path');
assert(cycle.blocked.some(x=>x.reason==='cycle'),'Cycle should be reported');
console.log('Phase 3 pathfinder tests passed');
